### PR TITLE
Fixed board member image path and some issues in the case form

### PR DESCRIPTION
**Pull request by vidurangaw**

### CODE REVIEW

**Comment by vidurangaw** [comment]
@meshulam 
Thanks
We also need to the update the env file with Twitter credentials. Shall I email it?

**Comment by meshulam** [comment]
Cool, was just going to ask about that. We configure those in Elastic Beanstalk. I'll check with Tracy about giving you AWS access and you can add them in the web UI.

**Comment by meshulam** [comment]
@vidurangaw is `vpowerrc@gmail.com` the right address to send login info?

**Comment by vidurangaw** [comment]
yes

**Pull request merged**
